# Pandas library

In [1]:
import pandas as pd  # first step

In [8]:
# import dataset by clipboarding
df = pd.read_clipboard()
df           # only used fro quick analysis

   Name,Age,Heigth
0  Muhammad,12,6.0
1       Ali,30,5.5
2     Soban,26,6.0
3    Hamdan,46,7.0
4    Nibras,23,5.4

### Importing datasets from excel

In [7]:
df_excel = pd.read_excel("../00_datasets/titanic_df.xlsx")
df_excel

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

## import csv files

In [8]:
df_csv = pd.read_csv("../00_datasets/microbial.csv")
df_csv

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
0,0,P. aeruginosa,Vancomycin,83.740294,Africa,2018,52,F,Urinary,9,5,110
1,1,A. baumannii,Methicillin,54.298686,North America,2019,93,F,Urinary,9,0,99
2,2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
3,3,A. baumannii,Amoxicillin,45.493537,Asia,2018,72,M,NaN,14,10,365
4,4,A. baumannii,Amoxicillin,63.460719,Asia,2018,61,M,NaN,35,6,39
...,...,...,...,...,...,...,...,...,...,...,...,...
3495,3495,E. coli,Ciprofloxacin,44.199565,Asia,2018,38,M,NaN,19,6,104
3496,3496,A. baumannii,Ciprofloxacin,50.912172,Africa,2021,3,M,Urinary,2,3,365
3497,3497,E. coli,Vancomycin,90.270913,Asia,2018,16,F,Urinary,2,2,159
3498,3498,E. coli,Amoxicillin,47.194067,North America,2019,94,F,Respiratory,4,2,65
3499,3499,E. coli,Amoxicillin,59.293169,Africa,2020,40,F,NaN,0,15,111

## import tsv data

In [9]:
df_txt = pd.read_csv('../00_datasets/microbial.tsv', sep='\t')
df_txt

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
0,0,P. aeruginosa,Vancomycin,83.740294,Africa,2018,52,F,Urinary,9,5,110
1,1,A. baumannii,Methicillin,54.298686,North America,2019,93,F,Urinary,9,0,99
2,2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
3,3,A. baumannii,Amoxicillin,45.493537,Asia,2018,72,M,NaN,14,10,365
4,4,A. baumannii,Amoxicillin,63.460719,Asia,2018,61,M,NaN,35,6,39
...,...,...,...,...,...,...,...,...,...,...,...,...
3495,3495,E. coli,Ciprofloxacin,44.199565,Asia,2018,38,M,NaN,19,6,104
3496,3496,A. baumannii,Ciprofloxacin,50.912172,Africa,2021,3,M,Urinary,2,3,365
3497,3497,E. coli,Vancomycin,90.270913,Asia,2018,16,F,Urinary,2,2,159
3498,3498,E. coli,Amoxicillin,47.194067,North America,2019,94,F,Respiratory,4,2,65
3499,3499,E. coli,Amoxicillin,59.293169,Africa,2020,40,F,NaN,0,15,111

# Dummy Dataset

In [13]:
# create dataframe from dictionary 
df = {'Name':['Muhammad', 'Ali', 'Soban', 'Hamdan', 'Nibras'],
      'Age':[12,30,26,46,23],
      'Heigth':[6,5.5,6,7,5.4]}  #heigth is in inches
df
df_2= pd.DataFrame(df)
df_2

       Name  Age  Heigth
0  Muhammad   12     6.0
1       Ali   30     5.5
2     Soban   26     6.0
3    Hamdan   46     7.0
4    Nibras   23     5.4

## making json datasets

In [2]:
df_json = {
  "company": "Nexus Media Group",
  "metadata": {
    "version": "2.4.1",
    "generatedAt": "2026-07-17T18:22:00Z",
    "totalRecords": 3
  },
  "employees": [
    {
      "id": "EMP-0091",
      "personal": {
        "firstName": "Sarah",
        "lastName": "Chen",
        "age": 34,
        "contact": {
          "email": "s.chen@nexusmedia.com",
          "phone": "+1-555-019-2834",
          "address": {
            "street": "742 Evergreen Terrace",
            "city": "Springfield",
            "state": "IL",
            "zipCode": "62704"
          }
        }
      },
      "employment": {
        "role": "Lead Data Scientist",
        "department": "Analytics",
        "salary": 135000,
        "isRemote": True,
        "startDate": "2021-04-12",
        "skills": ["Python", "SQL", "Machine Learning", "PyTorch", "Tableau"]
      },
      "projects": [
        {
          "projectId": "PRJ-901",
          "name": "Predictive Churn Model",
          "status": "Completed",
          "budget": 45000.00
        },
        {
          "projectId": "PRJ-905",
          "name": "Automated Content Tagging",
          "status": "In Progress",
          "budget": 120000.50
        }
      ]
    },
    {
      "id": "EMP-0092",
      "personal": {
        "firstName": "Marcus",
        "lastName": "Rodriguez",
        "age": 29,
        "contact": {
          "email": "m.rodriguez@nexusmedia.com",
          "phone": "+1-555-014-7721",
          "address": {
            "street": "112 Ocean Drive",
            "city": "Miami",
            "state": "FL",
            "zipCode": "33139"
          }
        }
      },
      "employment": {
        "role": "Senior DevOps Engineer",
        "department": "Infrastructure",
        "salary": 142000,
        "isRemote": False,
        "startDate": "2023-09-01",
        "skills": ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD"]
      },
      "projects": [
        {
          "projectId": "PRJ-702",
          "name": "Cloud Migration Phase 2",
          "status": "In Progress",
          "budget": 350000.00
        }
      ]
    },
    {
      "id": "EMP-0093",
      "personal": {
        "firstName": "Elena",
        "lastName": "Rostova",
        "age": 41,
        "contact": {
          "email": "e.rostova@nexusmedia.com",
          "phone": "+1-555-016-9988",
          "address": {
            "street": "456 Maple Avenue",
            "city": "Boston",
            "state": "MA",
            "zipCode": "02115"
          }
        }
      },
      "employment": {
        "role": "Product Director",
        "department": "Product Management",
        "salary": 165000,
        "isRemote": True,
        "startDate": "2018-11-15",
        "skills": ["Agile", "Scrum", "Roadmapping", "UI/UX Strategy"]
      },
      "projects": [
        {
          "projectId": "PRJ-501",
          "name": "Mobile App Redesign",
          "status": "Planning",
          "budget": 85000.00
        }
      ]
    }
  ],
  "systemSettings": {
    "allowedRoles": ["Admin", "Manager", "Employee", "Guest"],
    "security": {
      "twoFactorAuth": True,
      "sessionTimeoutMinutes": 30,
      "ipWhitelist": ["192.168.1.1", "10.0.0.1"]
    }
  }
}

df_json

{'company': 'Nexus Media Group',
 'metadata': {'version': '2.4.1',
  'generatedAt': '2026-07-17T18:22:00Z',
  'totalRecords': 3},
 'employees': [{'id': 'EMP-0091',
   'personal': {'firstName': 'Sarah',
    'lastName': 'Chen',
    'age': 34,
    'contact': {'email': 's.chen@nexusmedia.com',
     'phone': '+1-555-019-2834',
     'address': {'street': '742 Evergreen Terrace',
      'city': 'Springfield',
      'state': 'IL',
      'zipCode': '62704'}}},
   'employment': {'role': 'Lead Data Scientist',
    'department': 'Analytics',
    'salary': 135000,
    'isRemote': True,
    'startDate': '2021-04-12',
    'skills': ['Python', 'SQL', 'Machine Learning', 'PyTorch', 'Tableau']},
   'projects': [{'projectId': 'PRJ-901',
     'name': 'Predictive Churn Model',
     'status': 'Completed',
     'budget': 45000.0},
    {'projectId': 'PRJ-905',
     'name': 'Automated Content Tagging',
     'status': 'In Progress',
     'budget': 120000.5}]},
  {'id': 'EMP-0092',
   'personal': {'firstName': 'Marcus',
    'lastName': 'Rodriguez',
    'age': 29,
    'contact': {'email': 'm.rodriguez@nexusmedia.com',
     'phone': '+1-555-014-7721',
     'address': {'street': '112 Ocean Drive',
      'city': 'Miami',
      'state': 'FL',
      'zipCode': '33139'}}},
   'employment': {'role': 'Senior DevOps Engineer',
    'department': 'Infrastructure',
    'salary': 142000,
    'isRemote': False,
    'startDate': '2023-09-01',
    'skills': ['AWS', 'Docker', 'Kubernetes', 'Terraform', 'CI/CD']},
   'projects': [{'projectId': 'PRJ-702',
     'name': 'Cloud Migration Phase 2',
     'status': 'In Progress',
     'budget': 350000.0}]},
  {'id': 'EMP-0093',
   'personal': {'firstName': 'Elena',
    'lastName': 'Rostova',
    'age': 41,
    'contact': {'email': 'e.rostova@nexusmedia.com',
     'phone': '+1-555-016-9988',
     'address': {'street': '456 Maple Avenue',
      'city': 'Boston',
      'state': 'MA',
      'zipCode': '02115'}}},
   'employment': {'role': 'Product Director',
    'department': 'Product Management',
    'salary': 165000,
    'isRemote': True,
    'startDate': '2018-11-15',
    'skills': ['Agile', 'Scrum', 'Roadmapping', 'UI/UX Strategy']},
   'projects': [{'projectId': 'PRJ-501',
     'name': 'Mobile App Redesign',
     'status': 'Planning',
     'budget': 85000.0}]}],
 'systemSettings': {'allowedRoles': ['Admin', 'Manager', 'Employee', 'Guest'],
  'security': {'twoFactorAuth': True,
   'sessionTimeoutMinutes': 30,
   'ipWhitelist': ['192.168.1.1', '10.0.0.1']}}}

In [4]:
df_json
##save the datasets
import json #this build in library

with open('../00_datasets/0.1_pandas_practice_datasets/employee.json', 'w') as f:
	json.dump(df_json, f, indent=2)

import pandas as pd

## view pandas the cleanest way to save the json file	
df_employees = pd.json_normalize(df_json['employees']) # convert the employees list into a DataFrame 

df_employees.to_json('../00_datasets/0.1_pandas_practice_datasets/employee_1.json', orient='records') # and save via pandas

In [ ]:
df_2.to_clipboard()

##### convert dataframe into file by using pandas command

In [10]:
df.to_excel('../00_datasets/0.1_pandas_practice_datasets/people.xlsx', index=False)
df.to_csv('../00_datasets/0.1_pandas_practice_datasets/people.csv', index=False)

## Reading data from path

In [1]:
import pandas as pd

In [ ]:
#step 1: Change the '\' into '/' "C:\Users\mhusm\Documents\Python_for_data_science\00_datasets\titanic.xlsx"
df = pd.read_excel("C:/Users/mhusm/Documents/Python_for_data_science/00_datasets/titanic.xlsx")
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df = pd.read_excel(r"C:\Users\mhusm\Documents\Python_for_data_science\00_datasets\titanic.xlsx", sheet_name=0)
df    ## here r is teh string literal and 'sheet_name' function is used to access the sheet no.'by using name or index

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

**r** in pandas show that the path is raw literal string so python treat it as **literal character** rather than **escape character** because '\' it is used to break the string..... such as if we used '\n' means add in new line or if used '\t' means add space

In [ ]:
# example with \
print("Hello "world" !")  ## here python think that string is end at second " marks

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1256022707.py, line 2)

In [10]:
# with \
print("Hello \"world\" !")

Hello "world" !

\n = Starts a new line.\
\t = Inserts a tab space\

you can also read file, having space between name of file e.g "world population", but best practice is that used '_' between name such as "world_population"

In [14]:
df = pd.read_csv(r"C:\Users\mhusm\Documents\Python_for_data_science\00_datasets\micro bial.csv")
df

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
0,0,P. aeruginosa,Vancomycin,83.740294,Africa,2018,52,F,Urinary,9,5,110
1,1,A. baumannii,Methicillin,54.298686,North America,2019,93,F,Urinary,9,0,99
2,2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
3,3,A. baumannii,Amoxicillin,45.493537,Asia,2018,72,M,NaN,14,10,365
4,4,A. baumannii,Amoxicillin,63.460719,Asia,2018,61,M,NaN,35,6,39
...,...,...,...,...,...,...,...,...,...,...,...,...
3495,3495,E. coli,Ciprofloxacin,44.199565,Asia,2018,38,M,NaN,19,6,104
3496,3496,A. baumannii,Ciprofloxacin,50.912172,Africa,2021,3,M,Urinary,2,3,365
3497,3497,E. coli,Vancomycin,90.270913,Asia,2018,16,F,Urinary,2,2,159
3498,3498,E. coli,Amoxicillin,47.194067,North America,2019,94,F,Respiratory,4,2,65
3499,3499,E. coli,Amoxicillin,59.293169,Africa,2020,40,F,NaN,0,15,111

### Reading tabular dataset

In [8]:
import pandas as pd

df_tabuler = pd.read_table('../00_datasets/microbial.tsv', sep = '\t', header=0)

df_tabuler

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
0,0,P. aeruginosa,Vancomycin,83.740294,Africa,2018,52,F,Urinary,9,5,110
1,1,A. baumannii,Methicillin,54.298686,North America,2019,93,F,Urinary,9,0,99
2,2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
3,3,A. baumannii,Amoxicillin,45.493537,Asia,2018,72,M,NaN,14,10,365
4,4,A. baumannii,Amoxicillin,63.460719,Asia,2018,61,M,NaN,35,6,39
...,...,...,...,...,...,...,...,...,...,...,...,...
3495,3495,E. coli,Ciprofloxacin,44.199565,Asia,2018,38,M,NaN,19,6,104
3496,3496,A. baumannii,Ciprofloxacin,50.912172,Africa,2021,3,M,Urinary,2,3,365
3497,3497,E. coli,Vancomycin,90.270913,Asia,2018,16,F,Urinary,2,2,159
3498,3498,E. coli,Amoxicillin,47.194067,North America,2019,94,F,Respiratory,4,2,65
3499,3499,E. coli,Amoxicillin,59.293169,Africa,2020,40,F,NaN,0,15,111

In [9]:
## reading csv via table function
import pandas as pd

df_csv = pd.read_table('../00_datasets/microbial.csv', sep = ',', header=0)

df_csv

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
0,0,P. aeruginosa,Vancomycin,83.740294,Africa,2018,52,F,Urinary,9,5,110
1,1,A. baumannii,Methicillin,54.298686,North America,2019,93,F,Urinary,9,0,99
2,2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
3,3,A. baumannii,Amoxicillin,45.493537,Asia,2018,72,M,NaN,14,10,365
4,4,A. baumannii,Amoxicillin,63.460719,Asia,2018,61,M,NaN,35,6,39
...,...,...,...,...,...,...,...,...,...,...,...,...
3495,3495,E. coli,Ciprofloxacin,44.199565,Asia,2018,38,M,NaN,19,6,104
3496,3496,A. baumannii,Ciprofloxacin,50.912172,Africa,2021,3,M,Urinary,2,3,365
3497,3497,E. coli,Vancomycin,90.270913,Asia,2018,16,F,Urinary,2,2,159
3498,3498,E. coli,Amoxicillin,47.194067,North America,2019,94,F,Respiratory,4,2,65
3499,3499,E. coli,Amoxicillin,59.293169,Africa,2020,40,F,NaN,0,15,111

### Reading json file

In [ ]:
import pandas as pd 

df_json = pd.read_json('../00_datasets/0.1_pandas_practice_datasets/employee_1.json')

df_json

,id,projects,personal.firstName,personal.lastName,personal.age,personal.contact.email,personal.contact.phone,personal.contact.address.street,personal.contact.address.city,personal.contact.address.state,personal.contact.address.zipCode,employment.role,employment.department,employment.salary,employment.isRemote,employment.startDate,employment.skills
0,EMP-0091,"[{'projectId': 'PRJ-901', 'name': 'Predictive ...",Sarah,Chen,34,s.chen@nexusmedia.com,+1-555-019-2834,742 Evergreen Terrace,Springfield,IL,62704,Lead Data Scientist,Analytics,135000,True,2021-04-12,"[Python, SQL, Machine Learning, PyTorch, Tableau]"
1,EMP-0092,"[{'projectId': 'PRJ-702', 'name': 'Cloud Migra...",Marcus,Rodriguez,29,m.rodriguez@nexusmedia.com,+1-555-014-7721,112 Ocean Drive,Miami,FL,33139,Senior DevOps Engineer,Infrastructure,142000,False,2023-09-01,"[AWS, Docker, Kubernetes, Terraform, CI/CD]"
2,EMP-0093,"[{'projectId': 'PRJ-501', 'name': 'Mobile App ...",Elena,Rostova,41,e.rostova@nexusmedia.com,+1-555-016-9988,456 Maple Avenue,Boston,MA,2115,Product Director,Product Management,165000,True,2018-11-15,"[Agile, Scrum, Roadmapping, UI/UX Strategy]"