# Subsetting datasets

In [3]:
import pandas as pd

df = pd.read_csv('../00_datasets/microbial.csv')
df

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
0,0,P. aeruginosa,Vancomycin,83.740294,Africa,2018,52,F,Urinary,9,5,110
1,1,A. baumannii,Methicillin,54.298686,North America,2019,93,F,Urinary,9,0,99
2,2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
3,3,A. baumannii,Amoxicillin,45.493537,Asia,2018,72,M,NaN,14,10,365
4,4,A. baumannii,Amoxicillin,63.460719,Asia,2018,61,M,NaN,35,6,39
...,...,...,...,...,...,...,...,...,...,...,...,...
3495,3495,E. coli,Ciprofloxacin,44.199565,Asia,2018,38,M,NaN,19,6,104
3496,3496,A. baumannii,Ciprofloxacin,50.912172,Africa,2021,3,M,Urinary,2,3,365
3497,3497,E. coli,Vancomycin,90.270913,Asia,2018,16,F,Urinary,2,2,159
3498,3498,E. coli,Amoxicillin,47.194067,North America,2019,94,F,Respiratory,4,2,65
3499,3499,E. coli,Amoxicillin,59.293169,Africa,2020,40,F,NaN,0,15,111

In [4]:
# subset on the basis of column
bacteria = df['bacteria']

print(type(bacteria))

bacteria

<class 'pandas.core.series.Series'>

0       P. aeruginosa
1        A. baumannii
2       K. pneumoniae
3        A. baumannii
4        A. baumannii
            ...
3495          E. coli
3496     A. baumannii
3497          E. coli
3498          E. coli
3499          E. coli
Name: bacteria, Length: 3500, dtype: object

In [5]:
# subset multiple column in dataset
df_bac_antibio = df[["bacteria", "antibiotic"]]

print(type(df_bac_antibio))
df_bac_antibio

<class 'pandas.core.frame.DataFrame'>

           bacteria     antibiotic
0     P. aeruginosa     Vancomycin
1      A. baumannii    Methicillin
2     K. pneumoniae    Methicillin
3      A. baumannii    Amoxicillin
4      A. baumannii    Amoxicillin
...             ...            ...
3495        E. coli  Ciprofloxacin
3496   A. baumannii  Ciprofloxacin
3497        E. coli     Vancomycin
3498        E. coli    Amoxicillin
3499        E. coli    Amoxicillin

[3500 rows x 2 columns]

In [6]:
## subsetting with rows
import pandas as pd

K_pneu = df["bacteria"] == "K. pneumoniae"
K_pneu   ## if yo are using on single []

0       False
1       False
2        True
3       False
4       False
        ...
3495    False
3496    False
3497    False
3498    False
3499    False
Name: bacteria, Length: 3500, dtype: bool

In [7]:
import pandas as pd

K_pneu = df[df["bacteria"] == "K. pneumoniae"]
K_pneu   ## if yo are using on double []

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
2,2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
6,6,K. pneumoniae,Amoxicillin,90.978376,Africa,2021,83,F,NaN,9,3,24
7,7,K. pneumoniae,Vancomycin,71.214720,North America,2023,87,F,Respiratory,27,0,6
8,8,K. pneumoniae,Methicillin,59.115904,Europe,2019,75,M,NaN,6,6,91
11,11,K. pneumoniae,Methicillin,91.959423,Africa,2021,24,M,Urinary,23,3,365
...,...,...,...,...,...,...,...,...,...,...,...,...
3460,3460,K. pneumoniae,Meropenem,96.419665,Asia,2023,66,M,Respiratory,2,2,12
3468,3468,K. pneumoniae,Ciprofloxacin,100.000000,Africa,2018,40,M,Respiratory,8,11,68
3470,3470,K. pneumoniae,Meropenem,47.771810,South America,2020,76,M,Urinary,0,1,54
3481,3481,K. pneumoniae,Imipenem,79.746190,Africa,2021,77,M,NaN,5,14,179
3491,3491,K. pneumoniae,Meropenem,72.967774,Europe,2023,70,F,Urinary,7,3,365

In [8]:
# subsetting with more than one condition
df_kleb_methi = df[
	(df["bacteria"] == "K. pneumoniae") &
	(df["antibiotic"] == "Methicillin")
]
df_kleb_methi

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
2,2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
8,8,K. pneumoniae,Methicillin,59.115904,Europe,2019,75,M,NaN,6,6,91
11,11,K. pneumoniae,Methicillin,91.959423,Africa,2021,24,M,Urinary,23,3,365
133,133,K. pneumoniae,Methicillin,70.723281,Asia,2019,37,M,NaN,10,2,365
188,188,K. pneumoniae,Methicillin,43.005702,South America,2018,77,F,Blood,4,21,178
...,...,...,...,...,...,...,...,...,...,...,...,...
3268,3268,K. pneumoniae,Methicillin,82.943170,Africa,2019,73,F,NaN,2,4,7
3314,3314,K. pneumoniae,Methicillin,45.136757,Asia,2019,64,M,NaN,25,0,365
3329,3329,K. pneumoniae,Methicillin,100.000000,Africa,2021,81,F,NaN,11,9,96
3371,3371,K. pneumoniae,Methicillin,70.367988,North America,2018,72,M,Blood,1,1,108
3459,3459,K. pneumoniae,Methicillin,63.743472,Asia,2022,18,M,Urinary,13,5,140

In [11]:
##save the data
df_kleb_methi.to_csv('../00_datasets/0.1_pandas_practice_datasets/klebshela_methicillin', index=False)

In [3]:
import pandas as pd
df = pd.read_csv('../00_datasets/microbial.csv')

In [16]:
# kleb_methi_vanco = df[(df["bacteria"] == "K. pneumoniae") | (df["bacteria"] == "S. aureus")]

kleb_methi_vanco = df[df["bacteria"].isin(["K. pneumoniae", "S. aureus"])]
kleb_methi_vanco

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
2,2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
5,5,S. aureus,Penicillin,70.176834,South America,2019,21,M,Respiratory,4,1,29
6,6,K. pneumoniae,Amoxicillin,90.978376,Africa,2021,83,F,NaN,9,3,24
7,7,K. pneumoniae,Vancomycin,71.214720,North America,2023,87,F,Respiratory,27,0,6
8,8,K. pneumoniae,Methicillin,59.115904,Europe,2019,75,M,NaN,6,6,91
...,...,...,...,...,...,...,...,...,...,...,...,...
3470,3470,K. pneumoniae,Meropenem,47.771810,South America,2020,76,M,Urinary,0,1,54
3481,3481,K. pneumoniae,Imipenem,79.746190,Africa,2021,77,M,NaN,5,14,179
3485,3485,S. aureus,Meropenem,98.920064,Europe,2021,51,M,Respiratory,5,7,166
3490,3490,S. aureus,Ciprofloxacin,54.232354,South America,2020,84,F,Urinary,8,0,365
3491,3491,K. pneumoniae,Meropenem,72.967774,Europe,2023,70,F,Urinary,7,3,365

#### subsetting with known and unknown value

In [17]:
df

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
0,0,P. aeruginosa,Vancomycin,83.740294,Africa,2018,52,F,Urinary,9,5,110
1,1,A. baumannii,Methicillin,54.298686,North America,2019,93,F,Urinary,9,0,99
2,2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
3,3,A. baumannii,Amoxicillin,45.493537,Asia,2018,72,M,NaN,14,10,365
4,4,A. baumannii,Amoxicillin,63.460719,Asia,2018,61,M,NaN,35,6,39
...,...,...,...,...,...,...,...,...,...,...,...,...
3495,3495,E. coli,Ciprofloxacin,44.199565,Asia,2018,38,M,NaN,19,6,104
3496,3496,A. baumannii,Ciprofloxacin,50.912172,Africa,2021,3,M,Urinary,2,3,365
3497,3497,E. coli,Vancomycin,90.270913,Asia,2018,16,F,Urinary,2,2,159
3498,3498,E. coli,Amoxicillin,47.194067,North America,2019,94,F,Respiratory,4,2,65
3499,3499,E. coli,Amoxicillin,59.293169,Africa,2020,40,F,NaN,0,15,111

In [4]:
## for known value
prior_infect_site_known = df[df["prior_infection_site"].notnull()] ## or used notna()
prior_infect_site_known

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
0,0,P. aeruginosa,Vancomycin,83.740294,Africa,2018,52,F,Urinary,9,5,110
1,1,A. baumannii,Methicillin,54.298686,North America,2019,93,F,Urinary,9,0,99
2,2,K. pneumoniae,Methicillin,100.000000,Europe,2022,15,F,Respiratory,14,0,39
5,5,S. aureus,Penicillin,70.176834,South America,2019,21,M,Respiratory,4,1,29
7,7,K. pneumoniae,Vancomycin,71.214720,North America,2023,87,F,Respiratory,27,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...
3492,3492,E. faecium,Meropenem,45.774006,North America,2023,27,M,Respiratory,32,3,365
3494,3494,E. coli,Meropenem,100.000000,Asia,2020,93,F,Respiratory,8,0,365
3496,3496,A. baumannii,Ciprofloxacin,50.912172,Africa,2021,3,M,Urinary,2,3,365
3497,3497,E. coli,Vancomycin,90.270913,Asia,2018,16,F,Urinary,2,2,159
3498,3498,E. coli,Amoxicillin,47.194067,North America,2019,94,F,Respiratory,4,2,65

In [5]:
## for unknown value
prior_infect_site_unknown = df[df["prior_infection_site"].isna()] ## or used notna()
prior_infect_site_unknown

,Unnamed: 0,bacteria,antibiotic,resistance,region,year,age,gender,prior_infection_site,intensive_care_metrics,cumulative_days_on_antibiotic,days_since_last_hospital_stay
3,3,A. baumannii,Amoxicillin,45.493537,Asia,2018,72,M,NaN,14,10,365
4,4,A. baumannii,Amoxicillin,63.460719,Asia,2018,61,M,NaN,35,6,39
6,6,K. pneumoniae,Amoxicillin,90.978376,Africa,2021,83,F,NaN,9,3,24
8,8,K. pneumoniae,Methicillin,59.115904,Europe,2019,75,M,NaN,6,6,91
16,16,E. faecium,Penicillin,89.257775,Europe,2022,88,F,NaN,3,8,365
...,...,...,...,...,...,...,...,...,...,...,...,...
3486,3486,A. baumannii,Imipenem,76.915052,Asia,2021,73,M,NaN,18,10,365
3487,3487,A. baumannii,Imipenem,NaN,North America,2020,39,M,NaN,1,4,33
3493,3493,E. faecium,Imipenem,44.294687,North America,2023,2,F,NaN,6,0,28
3495,3495,E. coli,Ciprofloxacin,44.199565,Asia,2018,38,M,NaN,19,6,104
3499,3499,E. coli,Amoxicillin,59.293169,Africa,2020,40,F,NaN,0,15,111